### ISSUE TITLE
User Requests for Arjuna Updates

### ISSUE THREAD

**Issue by shangzhu-cmu** [ArjunaCluster/ArjunaUsers#11] opened 2021-07-22 19:17 UTC
This thread is created for making any requests for our cluster update in late August.

**Comment by shangzhu-cmu** [comment] 2021-07-22 19:18
CUDA version is a bit out-of-date (the one we currently have access to is 10.0). Will be great if we can install both CUDA 10.1 and CUDA 11.

**Comment by abillscmu** [comment] 2021-07-22 19:24
👍  = Approved
👎  = No
👀  = Maybe

**Comment by mkphuthi** [comment] 2021-07-22 20:34
I assume some this will be resolved with the OS update but having newer versions of gcc and libgcc would be nice. In general it would be nice to have newer versions (and some older versions) of common compilers (GNU, openmpi, PGI, intel (unlikely since paid)) available as modules (to avoid path conflicts) if possible.

**Comment by abillscmu** [comment] 2021-07-22 21:18
If you could give us a very detailed list of exactly what you want, it will be quite helpful. Thanks for the suggestion!

**Comment by awadell1** [comment] 2021-07-23 14:32
Check out spack's current offerings: https://spack.readthedocs.io/en/latest/package_list.html

We do need to update some standard libs to get it to work, but would (hopefully) cover everyone's cuda, mpi, compiler requirements. Of course if you see something that's missing, that would be good to know

**Comment by rkurchin** [comment] 2021-07-23 15:37
Food for thought more than a specific request: https://singularity-hpc.readthedocs.io/en/latest/

I feel like this could be a useful thing to easily share configurations for various things in reproducible ways...

**Comment by abillscmu** [comment] 2021-07-23 15:43
Singularity is actually already installed, just not used very much AFAIK. There may be configuration issues, as I have not tested it.

**Comment by mkphuthi** [comment] 2021-07-23 16:05
My failed? attempt at an exhaustive list of requests given as name of spack package and version listed underneath. I would strongly recommend that they be available as modules that one can just `module load package` if not then this list is probably useless. Of course a lot of the things have dependencies so it would take some figuring to pick the order/versions.

### Things that are not on Arjuna right now but I think are important:
1. **nvhpc** - All CUDA tools
    21.7 or latest possible - This contains CUDA 10.2, 11.0, 11.4 and requires at least Nvidia driver version 440.33. If you don't want to update drivers you can get version 20.7 with current drivers. This should essentially cover everyone's CUDA needs except for special cases, specifically built for HPCs. This may need to be supplemented by a separate installation with CUDA 10.0 for people running older software. It seems like they only started making these SDKs with Cuda 10.1+
2. **gcc** - Compilers
 - latest
 - 7.40: to match current latest version of arjuna
 - 5.40: I think I've seen some cases where things don't work with newer versions than this
3. **elpa** - Speeds up most DFT packages
 - latest
 - 2016.05.004
4. bazel - Build tools
 - latest

### Things already on arjuna in some form:
Would it make sense to install two versions for these where possible i.e. same version as arjuna plus latest version?

anaconda3, scalapack, julia, lapack, openblas, openmp, openmpi, autotools, cmake, libxc, fftw, hdf5, matlab, mpich, intel (compilers), intel-mkl, intel-mpi (I'm not sure if there's an advantage to getting the intel-oneapi-* versions for all intel things), py-gpaw and lammps and quantum-espresso 6.7 (to avoid people having multiple, often very poorly built versions. Let me know if you build this so I can make recommendations for speed ups)

### Things that would be nice for me but are maybe not worth your trouble since I can install them myself:
gnuplot, VMD

### Note
If this affects people not in our group they will probably want to keep their installations and versions of VASP or other licensed software

**Closed** 2021-08-30 18:09 UTC
