### ISSUE TITLE
Multiple Nodes (All CPU + some GPU) Down

### ISSUE THREAD

**Issue by mkphuthi** [ArjunaCluster/ArjunaUsers#107] opened 2021-12-27 16:54 UTC
If an open issue already exists for the node, please do not submit a duplicate!

Node: d[001-024],f[001-024],e[001-004]
Date and Time you first noticed it was down: 12/26
Anything Else: Nope

**Comment by abillscmu** [comment] 2021-12-28 03:34
Closed as duplicate of #106

**Closed** 2021-12-28 03:34 UTC
