### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by maituoy** [ArjunaCluster/ArjunaUsers#54] opened 2021-09-13 14:18 UTC
Your Name: Maituo Yu
Your Andrew ID: maituoy
Node(s) on which the problem occurred:
Expected Behavior: job runs with multicore
Observed Behavior:job runs with 1 core
Location of Log file Showing the Error: /home/maituoy/software/interdispipe/example/alpha-Sn/PBE/scf
Location of Script showing [Minimum Working Example]:/home/maituoy/software/interdispipe/example/alpha-Sn/PBE/scf

Hi, how can we submit jobs with multicores currently? We used to use `mpirun`. But it results in an error with more than 2 cores specified. Here's my submission script and error message. 
<img width="559" alt="image" src="https://user-images.githubusercontent.com/37908868/133099762-ab4675ea-ef4c-48d2-9c0c-f5db272cdc20.png">
<img width="573" alt="image" src="https://user-images.githubusercontent.com/37908868/133099809-bb8391c1-1128-47de-ad94-fb0424a03ef3.png">
I also tried the `srun`. Although the job went through successfully with multicores set, the job only uses 1 core actually.

**Comment by abillscmu** [comment] 2021-09-13 15:47
Did you try it with 4 cores and 2 processes?
4 cores and 4 processes?

Did you try the --use-hwthread-cpus option as suggested by the message?

Which mpi are you using?

**Comment by maituoy** [comment] 2021-09-13 16:37
Sorry. I think I did not load the intel-mpi which results in this issue. 

I have one more question about the interactive jobs. It seems the modules are not loadable on the granted node because spack is not available on the computing node. Are there any solutions for that?

**Comment by abillscmu** [comment] 2021-09-13 16:48
They should be loadable. Can you provide an MWE?

**Comment by maituoy** [comment] 2021-09-13 16:51
![image](https://user-images.githubusercontent.com/37908868/133124663-142577ec-0443-4fbe-ad6c-ae7005a9eba7.png)

**Comment by abillscmu** [comment] 2021-09-13 17:01
I am able to reproduce this. If you do `srun <flags> --pty bash` for an interactive job spack will still work. Additionally, if you add spack to your path, you can use spack. use echo $PATH on the headnode to see where spack is. Another quick fix would be to add a line to your bashrc to export PATH.

**Comment by abillscmu** [comment] 2021-09-13 17:12
If you're curious, the basic issue here is that both srun and sbatch by default propagate environment variables, but by `salloc` and `ssh`, you don't have access to the spack variables needed to run these commands.

**Comment by maituoy** [comment] 2021-09-13 17:16
I see. Yeah, it works. Thank you!

**Comment by abillscmu** [comment] 2021-09-13 18:02
Great. I'm closing this, since I think we got through it. If there are any more issues, please open another issue!

**Closed by abillscmu** 2021-09-13 18:02 UTC
